
-- Data that we need to register with MapNotesIconLib
local MapNotesIconLib_Numbers_Icons = {
	[1] = {
		["title"]	= "Numbered Icons",
		["author"]	= "Telic",
		["date"]	= "20071227",
		["info"]	= {
			["enGB"] = "A Variety of Numbered Icons for MapNotes\n  (Some Icons courtesy of\n   http://www.freebuttons.com)",
		},
		["icons"]	= {
			{	["path"] = "Interface\\AddOns\\MapNotesIconLib_Numbers\\Icons\\Numbers\\SpotGroup0t", },
			{	["path"] = "Interface\\AddOns\\MapNotesIconLib_Numbers\\Icons\\Numbers\\SpotGroup1t", },
			{	["path"] = "Interface\\AddOns\\MapNotesIconLib_Numbers\\Icons\\Numbers\\SpotGroup2t", },
			{	["path"] = "Interface\\AddOns\\MapNotesIconLib_Numbers\\Icons\\Numbers\\SpotGroup3t", },
			{	["path"] = "Interface\\AddOns\\MapNotesIconLib_Numbers\\Icons\\Numbers\\SpotGroup4t", },
			{	["path"] = "Interface\\AddOns\\MapNotesIconLib_Numbers\\Icons\\Numbers\\SpotGroup5t", },
			{	["path"] = "Interface\\AddOns\\MapNotesIconLib_Numbers\\Icons\\Numbers\\SpotGroup6t", },
			{	["path"] = "Interface\\AddOns\\MapNotesIconLib_Numbers\\Icons\\Numbers\\SpotGroup7t", },
			{	["path"] = "Interface\\AddOns\\MapNotesIconLib_Numbers\\Icons\\Numbers\\SpotGroup8t", },
			{	["path"] = "Interface\\AddOns\\MapNotesIconLib_Numbers\\Icons\\Numbers\\SpotGroup9t", },
			{	["path"] = "Interface\\AddOns\\MapNotesIconLib_Numbers\\Icons\\Numbers\\Blank0", },
			{	["path"] = "Interface\\AddOns\\MapNotesIconLib_Numbers\\Icons\\Numbers\\Blank1", },
			{	["path"] = "Interface\\AddOns\\MapNotesIconLib_Numbers\\Icons\\Numbers\\Blank2", },
			{	["path"] = "Interface\\AddOns\\MapNotesIconLib_Numbers\\Icons\\Numbers\\Blank3", },
			{	["path"] = "Interface\\AddOns\\MapNotesIconLib_Numbers\\Icons\\Numbers\\Blank4", },
			{	["path"] = "Interface\\AddOns\\MapNotesIconLib_Numbers\\Icons\\Numbers\\Blank5", },
			{	["path"] = "Interface\\AddOns\\MapNotesIconLib_Numbers\\Icons\\Numbers\\Blank6", },
			{	["path"] = "Interface\\AddOns\\MapNotesIconLib_Numbers\\Icons\\Numbers\\Blank7", },
			{	["path"] = "Interface\\AddOns\\MapNotesIconLib_Numbers\\Icons\\Numbers\\Blank8", },
			{	["path"] = "Interface\\AddOns\\MapNotesIconLib_Numbers\\Icons\\Numbers\\Blank9", },
			{	["path"] = "Interface\\AddOns\\MapNotesIconLib_Numbers\\Icons\\Numbers\\Peacea00", },
			{	["path"] = "Interface\\AddOns\\MapNotesIconLib_Numbers\\Icons\\Numbers\\Peacea01", },
			{	["path"] = "Interface\\AddOns\\MapNotesIconLib_Numbers\\Icons\\Numbers\\Peacea02", },
			{	["path"] = "Interface\\AddOns\\MapNotesIconLib_Numbers\\Icons\\Numbers\\Peacea03", },
			{	["path"] = "Interface\\AddOns\\MapNotesIconLib_Numbers\\Icons\\Numbers\\Peacea04", },
			{	["path"] = "Interface\\AddOns\\MapNotesIconLib_Numbers\\Icons\\Numbers\\Peacea05", },
			{	["path"] = "Interface\\AddOns\\MapNotesIconLib_Numbers\\Icons\\Numbers\\Peacea06", },
			{	["path"] = "Interface\\AddOns\\MapNotesIconLib_Numbers\\Icons\\Numbers\\Peacea07", },
			{	["path"] = "Interface\\AddOns\\MapNotesIconLib_Numbers\\Icons\\Numbers\\Peacea08", },
			{	["path"] = "Interface\\AddOns\\MapNotesIconLib_Numbers\\Icons\\Numbers\\Peacea09", },
			{	["path"] = "Interface\\AddOns\\MapNotesIconLib_Numbers\\Icons\\Numbers\\Peaceb00", },
			{	["path"] = "Interface\\AddOns\\MapNotesIconLib_Numbers\\Icons\\Numbers\\Peaceb01", },
			{	["path"] = "Interface\\AddOns\\MapNotesIconLib_Numbers\\Icons\\Numbers\\Peaceb02", },
			{	["path"] = "Interface\\AddOns\\MapNotesIconLib_Numbers\\Icons\\Numbers\\Peaceb03", },
			{	["path"] = "Interface\\AddOns\\MapNotesIconLib_Numbers\\Icons\\Numbers\\Peaceb04", },
			{	["path"] = "Interface\\AddOns\\MapNotesIconLib_Numbers\\Icons\\Numbers\\Peaceb05", },
			{	["path"] = "Interface\\AddOns\\MapNotesIconLib_Numbers\\Icons\\Numbers\\Peaceb06", },
			{	["path"] = "Interface\\AddOns\\MapNotesIconLib_Numbers\\Icons\\Numbers\\Peaceb07", },
			{	["path"] = "Interface\\AddOns\\MapNotesIconLib_Numbers\\Icons\\Numbers\\Peaceb08", },
			{	["path"] = "Interface\\AddOns\\MapNotesIconLib_Numbers\\Icons\\Numbers\\Peaceb09", },
			{	["path"] = "Interface\\AddOns\\MapNotesIconLib_Numbers\\Icons\\Numbers\\Peacec00", },
			{	["path"] = "Interface\\AddOns\\MapNotesIconLib_Numbers\\Icons\\Numbers\\Peacec01", },
			{	["path"] = "Interface\\AddOns\\MapNotesIconLib_Numbers\\Icons\\Numbers\\Peacec02", },
			{	["path"] = "Interface\\AddOns\\MapNotesIconLib_Numbers\\Icons\\Numbers\\Peacec03", },
			{	["path"] = "Interface\\AddOns\\MapNotesIconLib_Numbers\\Icons\\Numbers\\Peacec04", },
			{	["path"] = "Interface\\AddOns\\MapNotesIconLib_Numbers\\Icons\\Numbers\\Peacec05", },
			{	["path"] = "Interface\\AddOns\\MapNotesIconLib_Numbers\\Icons\\Numbers\\Peacec06", },
			{	["path"] = "Interface\\AddOns\\MapNotesIconLib_Numbers\\Icons\\Numbers\\Peacec07", },
			{	["path"] = "Interface\\AddOns\\MapNotesIconLib_Numbers\\Icons\\Numbers\\Peacec08", },
			{	["path"] = "Interface\\AddOns\\MapNotesIconLib_Numbers\\Icons\\Numbers\\Peacec09", },
			{	["path"] = "Interface\\AddOns\\MapNotesIconLib_Numbers\\Icons\\Numbers\\Peaced00", },
			{	["path"] = "Interface\\AddOns\\MapNotesIconLib_Numbers\\Icons\\Numbers\\Peaced01", },
			{	["path"] = "Interface\\AddOns\\MapNotesIconLib_Numbers\\Icons\\Numbers\\Peaced02", },
			{	["path"] = "Interface\\AddOns\\MapNotesIconLib_Numbers\\Icons\\Numbers\\Peaced03", },
			{	["path"] = "Interface\\AddOns\\MapNotesIconLib_Numbers\\Icons\\Numbers\\Peaced04", },
			{	["path"] = "Interface\\AddOns\\MapNotesIconLib_Numbers\\Icons\\Numbers\\Peaced05", },
			{	["path"] = "Interface\\AddOns\\MapNotesIconLib_Numbers\\Icons\\Numbers\\Peaced06", },
			{	["path"] = "Interface\\AddOns\\MapNotesIconLib_Numbers\\Icons\\Numbers\\Peaced07", },
			{	["path"] = "Interface\\AddOns\\MapNotesIconLib_Numbers\\Icons\\Numbers\\Peaced08", },
			{	["path"] = "Interface\\AddOns\\MapNotesIconLib_Numbers\\Icons\\Numbers\\Peaced09", },
			{	["path"] = "Interface\\AddOns\\MapNotesIconLib_Numbers\\Icons\\Numbers\\Peacee00", },
			{	["path"] = "Interface\\AddOns\\MapNotesIconLib_Numbers\\Icons\\Numbers\\Peacee01", },
			{	["path"] = "Interface\\AddOns\\MapNotesIconLib_Numbers\\Icons\\Numbers\\Peacee02", },
			{	["path"] = "Interface\\AddOns\\MapNotesIconLib_Numbers\\Icons\\Numbers\\Peacee03", },
			{	["path"] = "Interface\\AddOns\\MapNotesIconLib_Numbers\\Icons\\Numbers\\Peacee04", },
			{	["path"] = "Interface\\AddOns\\MapNotesIconLib_Numbers\\Icons\\Numbers\\Peacee05", },
			{	["path"] = "Interface\\AddOns\\MapNotesIconLib_Numbers\\Icons\\Numbers\\Peacee06", },
			{	["path"] = "Interface\\AddOns\\MapNotesIconLib_Numbers\\Icons\\Numbers\\Peacee07", },
			{	["path"] = "Interface\\AddOns\\MapNotesIconLib_Numbers\\Icons\\Numbers\\Peacee08", },
			{	["path"] = "Interface\\AddOns\\MapNotesIconLib_Numbers\\Icons\\Numbers\\Peacee09", },
			{	["path"] = "Interface\\AddOns\\MapNotesIconLib_Numbers\\Icons\\Numbers\\Peacef00", },
			{	["path"] = "Interface\\AddOns\\MapNotesIconLib_Numbers\\Icons\\Numbers\\Peacef01", },
			{	["path"] = "Interface\\AddOns\\MapNotesIconLib_Numbers\\Icons\\Numbers\\Peacef02", },
			{	["path"] = "Interface\\AddOns\\MapNotesIconLib_Numbers\\Icons\\Numbers\\Peacef03", },
			{	["path"] = "Interface\\AddOns\\MapNotesIconLib_Numbers\\Icons\\Numbers\\Peacef04", },
			{	["path"] = "Interface\\AddOns\\MapNotesIconLib_Numbers\\Icons\\Numbers\\Peacef05", },
			{	["path"] = "Interface\\AddOns\\MapNotesIconLib_Numbers\\Icons\\Numbers\\Peacef06", },
			{	["path"] = "Interface\\AddOns\\MapNotesIconLib_Numbers\\Icons\\Numbers\\Peacef07", },
			{	["path"] = "Interface\\AddOns\\MapNotesIconLib_Numbers\\Icons\\Numbers\\Peacef08", },
			{	["path"] = "Interface\\AddOns\\MapNotesIconLib_Numbers\\Icons\\Numbers\\Peacef09", },
			{	["path"] = "Interface\\AddOns\\MapNotesIconLib_Numbers\\Icons\\Numbers\\Marblea00", },
			{	["path"] = "Interface\\AddOns\\MapNotesIconLib_Numbers\\Icons\\Numbers\\Marblea01", },
			{	["path"] = "Interface\\AddOns\\MapNotesIconLib_Numbers\\Icons\\Numbers\\Marblea02", },
			{	["path"] = "Interface\\AddOns\\MapNotesIconLib_Numbers\\Icons\\Numbers\\Marblea03", },
			{	["path"] = "Interface\\AddOns\\MapNotesIconLib_Numbers\\Icons\\Numbers\\Marblea04", },
			{	["path"] = "Interface\\AddOns\\MapNotesIconLib_Numbers\\Icons\\Numbers\\Marblea05", },
			{	["path"] = "Interface\\AddOns\\MapNotesIconLib_Numbers\\Icons\\Numbers\\Marblea06", },
			{	["path"] = "Interface\\AddOns\\MapNotesIconLib_Numbers\\Icons\\Numbers\\Marblea07", },
			{	["path"] = "Interface\\AddOns\\MapNotesIconLib_Numbers\\Icons\\Numbers\\Marblea08", },
			{	["path"] = "Interface\\AddOns\\MapNotesIconLib_Numbers\\Icons\\Numbers\\Marblea09", },
			{	["path"] = "Interface\\AddOns\\MapNotesIconLib_Numbers\\Icons\\Numbers\\Marbleb00", },
			{	["path"] = "Interface\\AddOns\\MapNotesIconLib_Numbers\\Icons\\Numbers\\Marbleb01", },
			{	["path"] = "Interface\\AddOns\\MapNotesIconLib_Numbers\\Icons\\Numbers\\Marbleb02", },
			{	["path"] = "Interface\\AddOns\\MapNotesIconLib_Numbers\\Icons\\Numbers\\Marbleb03", },
			{	["path"] = "Interface\\AddOns\\MapNotesIconLib_Numbers\\Icons\\Numbers\\Marbleb04", },
			{	["path"] = "Interface\\AddOns\\MapNotesIconLib_Numbers\\Icons\\Numbers\\Marbleb05", },
			{	["path"] = "Interface\\AddOns\\MapNotesIconLib_Numbers\\Icons\\Numbers\\Marbleb06", },
			{	["path"] = "Interface\\AddOns\\MapNotesIconLib_Numbers\\Icons\\Numbers\\Marbleb07", },
			{	["path"] = "Interface\\AddOns\\MapNotesIconLib_Numbers\\Icons\\Numbers\\Marbleb08", },
			{	["path"] = "Interface\\AddOns\\MapNotesIconLib_Numbers\\Icons\\Numbers\\Marbleb09", },
			{	["path"] = "Interface\\AddOns\\MapNotesIconLib_Numbers\\Icons\\Numbers\\Marblec00", },
			{	["path"] = "Interface\\AddOns\\MapNotesIconLib_Numbers\\Icons\\Numbers\\Marblec01", },
			{	["path"] = "Interface\\AddOns\\MapNotesIconLib_Numbers\\Icons\\Numbers\\Marblec02", },
			{	["path"] = "Interface\\AddOns\\MapNotesIconLib_Numbers\\Icons\\Numbers\\Marblec03", },
			{	["path"] = "Interface\\AddOns\\MapNotesIconLib_Numbers\\Icons\\Numbers\\Marblec04", },
			{	["path"] = "Interface\\AddOns\\MapNotesIconLib_Numbers\\Icons\\Numbers\\Marblec05", },
			{	["path"] = "Interface\\AddOns\\MapNotesIconLib_Numbers\\Icons\\Numbers\\Marblec06", },
			{	["path"] = "Interface\\AddOns\\MapNotesIconLib_Numbers\\Icons\\Numbers\\Marblec07", },
			{	["path"] = "Interface\\AddOns\\MapNotesIconLib_Numbers\\Icons\\Numbers\\Marblec08", },
			{	["path"] = "Interface\\AddOns\\MapNotesIconLib_Numbers\\Icons\\Numbers\\Marblec09", },
		},
	},
};



local MNIL_Numbers_Frame = CreateFrame("Frame");

local function MNIL_Numbers_OnEvent()
	MNIL_RegisterLibrary(MapNotesIconLib_Numbers_Icons);	-- The function needed to register the above data with MapNotesIconLib
end

MNIL_Numbers_Frame:RegisterEvent("VARIABLES_LOADED");
MNIL_Numbers_Frame:SetScript("OnEvent", MNIL_Numbers_OnEvent);

