local L = Rock("LibRockLocale-1.0"):GetTranslationNamespace("Cartographer_QuestInfo")

L:AddTranslations("zhTW", function() return {

-- Core.lua
	["Icon alpha"] = "圖示透明度",
	["Alpha transparency of the icon."] = "地圖上的圖示透明度。",
	["Icon size"] = "圖示大小",
	["Size of the icons on the map."] = "地圖上的圖示大小。",
	["Show minimap icons"] = "在小地圖上顯示",
	["Show quest icons on the minimap."] = "在小地圖上顯示任務圖示。",
	["Show all quest givers"] = "顯示所有任務委託人",
	["Show all quest givers, or just show givers around your level."] = "顯示所有任務委託人，不然只限於接近你等級的任務。",
	["Include giver's quest list"] = "顯示任務委託人的任務清單",
	["Include quest list when showing quest givers, or just show the number of quests (which is much faster)."] = "顯示任務委託人的任務清單，不然只顯示可接任務的數量(速度較快)。",
	["Show world map button"] = "顯示'任務資訊'按鈕",
	["Show button on the world map."] = "在世界地圖上顯示'任務資訊'的設定按鈕。",
	["Show quest level"] = "顯示任務等級",
	["Show quest level in quest log and NPC dialog."] = "在任務視窗及對話框顯示任務等級。",
	["Make quest log double wide"] = "加寬任務視窗",
	["Make the quest log window double wide, this will require UI reload."] = "加寬顯示任務視窗，注意:這功能需要重載UI後才能改變。",
	["Auto update quest icons"] = "自動更新任務圖示",
	["Auto update quest icons after quest or objective completed."] = "當任務或任務目標變動時，自動更新任務圖示。",
	["Update tracked quests only"] = "只更新已追蹤任務",
	["Update tracked quests only, or update all active quests."] = "只更新已追蹤任務，不然更新全部進行中任務。",
	["Quest Info"] = "任務資訊",
	["Module description"] = "提供任務資料",
	["GROUP"] = "團體",

-- LocationFrame.lua
	["Close"] = "關閉",

-- Map.lua
	["Quest Start"] = "任務開始",
	["Quest End"] = "任務結束",
	["Quest Giver"] = "任務委託人",
	["Quest Objective"] = "任務目標",
	["Show active quests"] = "標示進行中任務",
	["Show all info of active quests on current map."] = "在目前地圖上標示進行中的任務目標。",
	["Show tracked quests"] = "標示已追蹤任務",
	["Show all info of tracked quests on current map."] = "在目前地圖上標示已追蹤的任務目標。",
	["Show available quests"] = "標示可接的任務",
	["Show the givers of available quests on current map."] = "在目前地圖上標示可接的任務委託人。",
	["Clear quest icons"] = "清除任務圖示",
	["Clear quest icons generated by QuestInfo."] = "清除由任務資訊所產生的圖示。",
	["Open QuestInfo menu"] = "開啟任務資訊選項",
	["Alt-Click: "] = "Alt-點擊: ",
	["Shift-Click: "] = "Shift-點擊: ",
	["Elite"] = "精英",
	["Rare Elite"] = "稀有精英",
	["Boss"] = "首領",
	["Name:"] = "名稱:",
	["Objective:"] = "目標:",
	["Source:"] = "來源:",
	["Level:"] = "等級:",
	["Location:"] = "座標:",
	["Quests:"] = "任務:",
	["%d Quests"] = "%d個任務",

-- QuestFuPatch.lua
	["(done)"] = "(完成)",

-- QuestLogPatch.lua
	[" ..."] = " …",
	["... more"] = "… 還有更多",

-- SeriesFrame.lua
	["Quest Series"] = "系列任務",
	["Requires:"] = "需要等級:",
	["Sharable"] = "可分享",
	["Series:"] = "任務系列:",

} end)
