local L = Rock("LibRockLocale-1.0"):GetTranslationNamespace("Cartographer_QuestInfo")

L:AddTranslations("esES", function() return {

-- Core.lua
	["Icon alpha"] = "Transparencia de icono",
	["Alpha transparency of the icon."] = "Transparencia alfa del icono.",
	["Icon size"] = "Tamaño del icono",
	["Size of the icons on the map."] = "Tamaño de los iconos en el mapa.",
	["Show minimap icons"] = "Mostrar iconos en el minimapa",
	["Show quest icons on the minimap."] = "Mostrar iconos de misión en el minimapa.",
	["Show world map button"] = "Mostrar botón mapa del mundo",
	["Show button on the world map."] = "Mostrar botón en el mapa del mundo.",
	["Show quest level"] = "Mostrar nivel de misión",
	["Show quest level in quest log and NPC dialog."] = "Mostrar nivel de misión en el registro de misión y en el diálogo del NPC.",
	["Make quest log double wide"] = "Hacer registro de misiones de doble ancho",
	["Make the quest log window double wide, this will require UI reload."] = "Hace el registro de misiones de doble ancho, esto requiere recargar el UI.",
	["Quest Info"] = "Info Misión",
	["Module description"] = "Librería de Misión para localización de monstruos y otra información",
	["GROUP"] = GROUP,

-- LocationFrame.lua
	["Close"] = "Cerrar",

-- Map.lua
	["Quest Start"] = "Inicio de Misión",
	["Quest End"] = "Fin de Misión",
	["Quest Giver"] = "Proveedor de Misión",
	["Quest Objective"] = "Objetivo de Misión",
	["Show active quests"] = "Mostar misiones activas",
	["Show all info of active quests on current map."] = "Mostrar toda la información de las misiones activas en el mapa actual.",
	["Show available quests"] = "Mostrar misiones disponibles",
	["Show the givers of available quests on current map."] = "Mostrar los proveedores de las misiones disponibles en el mapa actual.",
	["Clear quest icons"] = "Limpiar iconos de misión",
	["Clear quest icons generated by QuestInfo."] = "Limpiar iconos de misión generados por QuestInfo",
	["Open QuestInfo menu"] = "Abrir menu de QuestInfo",
	["Alt-Click: "] = "Alt-Click: ",
	["Shift-Click: "] = "Mayús-Click: ",
	["Elite"] = "Élite",
	["Rare Elite"] = "Élite Raro",
	["Boss"] = "Jefe",
	["Name:"] = "Nombre:",
	["Objective:"] = "Objetivo:",
	["Source:"] = "Fuente:",
	["Level:"] = "Nivel:",
	["Location:"] = "Localización:",
	["Quests:"] = "Misiones:",
	["%d Quests"] = "%d Misiones",

-- QuestFuPatch.lua
	["(done)"] = "(hecho)",

-- QuestLogPatch.lua
	[" ..."] = " ...",
	["... more"] = "... más",

-- SeriesFrame.lua
	["Quest Series"] = "Serie de Misiones",
	["Requires:"] = "Requiere:",
	["Sharable"] = "Compartible",
	["Series:"] = "Serie:",
} end)
