-- Russian localization by StingerSoft (Eritnull aka Шептун)
local L = Rock("LibRockLocale-1.0"):GetTranslationNamespace("Cartographer_QuestInfo")

L:AddTranslations("ruRU", function() return {

-- Core.lua
	["Icon alpha"] = "Прозрачность иконки",
	["Alpha transparency of the icon."] = "Прозрачность иконки",
	["Icon size"] = "Размер иконки",
	["Size of the icons on the map."] = "Размер иконки на карте",
	["Show minimap icons"] = "Показ иконку у мини-карты",
	["Show quest icons on the minimap"] = "Показать иконку задания на мини-карте",
	["Show all quest givers"] = "Показ всех нипов с заданиями",
	["Show all quest givers, or just show givers around your level."] = "Показывать всех нипов с заданиями, или показать нипов с заданиями вашего уровня",
	["Include giver's quest list"] = "Включая список заданий НИПа",
	["Include quest list when showing quest givers, or just show the number of quests (which is much faster)."] = "Включая список заданий при показе НИПа, или число заданий (что намного быстрее)",
	["Show world map button"] = "Мировая карта",
	["Show button on the world map."] = "Отображать кнопку на мировой карте",
	["Show quest level"] = "Уровень задания",
	["Show quest level in quest log and NPC dialog."] = "Отображение уровня задания в журнале заданий и НИП диалогах.",
	["Make quest log double wide"] = "Сделать журнал заданий из двух секций",
	["Make the quest log window double wide, this will require UI reload."] = "Переделывает журнал заданий из стандартного в расширенный из двух секций, это потребует перезагрузит UI.",
	["Auto update quest icons"] = "Авто-обновление иконок",
	["Auto update quest icons after quest or objective completed."] = "Авто-обновление иконок после завершения задания или цели",
	["Update tracked quests only"] = "Обновлять только отслеживаемые задания",
	["Update tracked quests only, or update all active quests."] = "Обновлять только отслеживаемые задания, или обновлять все активные задания.",
	["Quest Info"] = "Инфо Задания",
	["Module description"] = "Библиотека заданий о местонахождение монстров и другой информации",
	["GROUP"] = "Группа",

-- LocationFrame.lua
	["Close"] = "Закрыть",

-- Map.lua
	["Quest Start"] = "Начало задания",
	["Quest End"] = "Конец задания",
	["Quest Giver"] = "Дающий задание",
	["Quest Objective"] = "Объект задания",
	["Show active quests"] = "Показать активные задания",
	["Show all info of active quests on current map."] = "Показать всю информацию о активных заданиях на текущей карте",
	["Show tracked quests"] = "Показать отслеживаемые задания",
	["Show all info of tracked quests on current map."] = "Показать всю информацию о отслеживаемых заданиях на текущей карте",
	["Show available quests"] = "Показать доступные задания",
	["Show the givers of available quests on current map."] = "Показать НИП с доступными заданиями на текущей карте",
	["Clear quest icons"] = "Очистить иконки задания",
	["Clear quest icons generated by QuestInfo."] = "Очистить иконки задания созданные ИнфоЗадания",
	["Open QuestInfo menu"] = "Открыть меню Инфо-Задания",
	["Alt-Click: "] = "Alt-Клик: ",
	["Shift-Click: "] = "Shift-Клик: ",
	["Elite"] = "Элита",
	["Rare Elite"] = "Редкий-Элита",
	["Boss"] = "Босс",
	["Name:"] = "Имя:",
	["Objective:"] = "Объект:",
	["Source:"] = "Источник:",
	["Level:"] = "Уровень:",
	["Location:"] = "Местоположение:",
	["Quests:"] = "Задания:",
	["%d Quests"] = "%d заданий",

-- QuestFuPatch.lua
	["(done)"] = "(выполненный)",

-- QuestLogPatch.lua
	[" ..."] = " ...",
	["... more"] = "... еще",

-- SeriesFrame.lua
	["Quest Series"] = "Серия заданий",
	["Requires:"] = "Требует:",
	["Sharable"] = "Совмест исп.",
	["Series:"] = "Серия:",
	
} end)
