
-- NameMap.lua: recipes named differently after learning
-- Auto generated on 8/9/2009 10:36:58 PM

RecipeRadar_NameMap = {

   ["enUS"] = {
      -- Alchemy
      ["Transmute: Arcanite"] = "Transmute Arcanite",
      ["Transmute: Iron to Gold"] = "Transmute Iron to Gold",
      ["Transmute: Mithril to Truesilver"] = "Transmute Mithril to Truesilver",
      ["Transmute: Fire to Earth"] = "Transmute Fire to Earth",
      ["Transmute: Air to Fire"] = "Transmute Air to Fire",
      ["Transmute: Earth to Water"] = "Transmute Earth to Water",
      ["Transmute: Water to Air"] = "Transmute Water to Air",
      ["Mighty Troll\'s Blood Elixir"] = "Major Troll\'s Blood Elixir",
      ["Transmute: Elemental Fire"] = "Transmute Elemental Fire",
      ["Transmute: Primal Air to Fire"] = "Transmute Primal Air to Fire",
      ["Transmute: Primal Earth to Water"] = "Transmute Primal Earth to Water",
      ["Transmute: Primal Fire to Earth"] = "Transmute Primal Fire to Earth",
      ["Transmute: Primal Might"] = "Transmute Primal Might",
      ["Transmute: Primal Water to Air"] = "Transmute Primal Water to Air",
      ["Transmute: Earthstorm Diamond"] = "Transmute Earthstorm Diamond",
      ["Transmute: Skyfire Diamond"] = "Transmute Skyfire Diamond",
      ["Transmute: Skyfire Diamond"] = "Transmute Skyfire Diamond",
      ["Transmute: Primal Fire to Earth"] = "Transmute Primal Fire to Earth",
      -- Enchanting
      ["Enchant 2H Weapon - Scourgebane"] = "Enchant Weapon - Scourgebane",
      ["Enchant Bracers - Superior Spellpower"] = "Enchant Bracer - Superior Spellpower",
      ["Enchant Bracers - Major Stamina"] = "Enchant Bracer - Major Stamina",
      -- Engineering
      ["Firework Cluster Launcher"] = "Cluster Launcher",
      -- Leatherworking
      ["Felstalker Bracer"] = "Felstalker Bracers",
      ["Felstalker Bracer"] = "Felstalker Bracers",
      -- Tailoring
      ["Festive Red Pant Suit"] = "Festival Suit",
      -- Jewelcrafting
      ["Figurine - Truesilver Crab"] = "Truesilver Crab",
      ["Figurine - Black Pearl Panther"] = "Black Pearl Panther",
      ["Figurine - Dawnstone Crab"] = "Dawnstone Crab",
      ["Figurine - Dawnstone Crab"] = "Dawnstone Crab",
      ["Figurine - Felsteel Boar"] = "Felsteel Boar",
      ["Figurine - Living Ruby Serpent"] = "Living Ruby Serpent",
      ["Figurine - Nightseye Panther"] = "Nightseye Panther",
      ["Figurine - Talasite Owl"] = "Talasite Owl",
   },

   ["enGB"] = {
      -- Alchemy
      ["Transmute: Arcanite"] = "Transmute Arcanite",
      ["Transmute: Iron to Gold"] = "Transmute Iron to Gold",
      ["Transmute: Mithril to Truesilver"] = "Transmute Mithril to Truesilver",
      ["Transmute: Fire to Earth"] = "Transmute Fire to Earth",
      ["Transmute: Air to Fire"] = "Transmute Air to Fire",
      ["Transmute: Earth to Water"] = "Transmute Earth to Water",
      ["Transmute: Water to Air"] = "Transmute Water to Air",
      ["Mighty Troll\'s Blood Elixir"] = "Major Troll\'s Blood Elixir",
      ["Transmute: Elemental Fire"] = "Transmute Elemental Fire",
      ["Transmute: Primal Air to Fire"] = "Transmute Primal Air to Fire",
      ["Transmute: Primal Earth to Water"] = "Transmute Primal Earth to Water",
      ["Transmute: Primal Fire to Earth"] = "Transmute Primal Fire to Earth",
      ["Transmute: Primal Might"] = "Transmute Primal Might",
      ["Transmute: Primal Water to Air"] = "Transmute Primal Water to Air",
      ["Transmute: Earthstorm Diamond"] = "Transmute Earthstorm Diamond",
      ["Transmute: Skyfire Diamond"] = "Transmute Skyfire Diamond",
      ["Transmute: Skyfire Diamond"] = "Transmute Skyfire Diamond",
      ["Transmute: Primal Fire to Earth"] = "Transmute Primal Fire to Earth",
      -- Enchanting
      ["Enchant 2H Weapon - Scourgebane"] = "Enchant Weapon - Scourgebane",
      ["Enchant Bracers - Superior Spellpower"] = "Enchant Bracer - Superior Spellpower",
      ["Enchant Bracers - Major Stamina"] = "Enchant Bracer - Major Stamina",
      -- Engineering
      ["Firework Cluster Launcher"] = "Cluster Launcher",
      -- Leatherworking
      ["Felstalker Bracer"] = "Felstalker Bracers",
      ["Felstalker Bracer"] = "Felstalker Bracers",
      -- Tailoring
      ["Festive Red Pant Suit"] = "Festival Suit",
      -- Jewelcrafting
      ["Figurine - Truesilver Crab"] = "Truesilver Crab",
      ["Figurine - Black Pearl Panther"] = "Black Pearl Panther",
      ["Figurine - Dawnstone Crab"] = "Dawnstone Crab",
      ["Figurine - Dawnstone Crab"] = "Dawnstone Crab",
      ["Figurine - Felsteel Boar"] = "Felsteel Boar",
      ["Figurine - Living Ruby Serpent"] = "Living Ruby Serpent",
      ["Figurine - Nightseye Panther"] = "Nightseye Panther",
      ["Figurine - Talasite Owl"] = "Talasite Owl",
   },

   ["deDE"] = {
      -- Alchemy
      ["Transmutieren: Arkanit"] = "Arkanit transmutieren",
      ["Transmutieren: Eisen in Gold"] = "Eisen in Gold transmutieren",
      ["Transmutieren: Mithril in Echtsilber"] = "Mithril in Echtsilber transmutieren",
      ["Transmutieren: Feuer zu Erde"] = "Feuer zu Erde transmutieren",
      ["Transmutieren: Luft zu Feuer"] = "Luft zu Feuer transmutieren",
      ["Transmutieren: Erde zu Wasser"] = "Erde zu Wasser transmutieren",
      ["Transmutieren: Wasser zu Luft"] = "Wasser zu Luft transmutieren",
      ["Mächtiges Trollblutelixier"] = "Erhebliches Trollblutelixier",
      ["Transmutieren: Urluft zu Urfeuer"] = "Urluft zu Urfeuer transmutieren",
      ["Transmutieren: Urerde zu Urwasser"] = "Urerde zu Urwasser transmutieren",
      ["Transmutieren: Urfeuer zu Urerde"] = "Urfeuer zu Urerde transmutieren",
      ["Transmutieren: Urmacht"] = "Urmacht transmutieren",
      ["Transmutieren: Urwasser zu Urluft"] = "Urwasser zu Urluft transmutieren",
      ["Transmutieren: Erdsturmdiamant"] = "Erdsturmdiamanten transmutieren",
      ["Transmutieren: Himmelsfeuerdiamant"] = "Himmelsfeuerdiamanten transmutieren",
      ["Transmutieren: Himmelsfeuerdiamant"] = "Himmelsfeuerdiamanten transmutieren",
      ["Transmutieren: Urfeuer zu Urerde"] = "Urfeuer zu Urerde transmutieren",
      -- Enchanting
      ["Handschuhe - Präzise Schläge"] = "Handschuhe - Präzise Stöße",
      ["Waffe - Lebensschutz"] = "Waffe - Lebenswächter",
      ["Zweihandwaffe - Geißelbann"] = "Waffe - Geißelbann",
      ["Armschiene - Höchste Ausdauer"] = "Armschiene - Erhebliche Ausdauer",
      -- Leatherworking
      ["Verzauberte Grollhufstiefel"] = "Verzauberte Grollschuppenstiefel",
      ["Handgelenksschützer der erlösten Seele"] = "Handgelenksschutz der erlösten Seele",
      -- Tailoring
      ["Festlicher roter Hosenanzug"] = "Festtagsanzug",
      -- Jewelcrafting
      ["Figur - Echtsilberkrebs"] = "Echtsilberkrebs",
      ["Figur - Schwarzer Perlenpanther"] = "Schwarzer Perlenpanther",
      ["Figur - Dämmersteinkrebs"] = "Dämmersteinkrebs",
      ["Figur - Dämmersteinkrebs"] = "Dämmersteinkrebs",
      ["Figur - Teufelsstahleber"] = "Teufelsstahleber",
      ["Figur - Lebendige Rubinschlange"] = "Lebendige Rubinschlange",
      ["Figur - Nachtaugenpanther"] = "Nachtaugenpanther",
      ["Figur - Talasiteule"] = "Talasiteule",
      ["Glänzender Golddraenit"] = "Brillantierter Golddraenit",
      ["Ring der scharlachroten Schatten"] = "Ring des scharlachroten Schattens",
   },

   ["frFR"] = {
      -- Alchemy
      ["Transmutation : Fer en Or"] = "Transmutation du fer en or",
      ["Transmutation : Mithril en Vrai-argent"] = "Transmutation du mithril en vrai-argent",
      ["Transmutation : Feu en Terre"] = "Transmutation du Feu en Terre",
      ["Transmutation : Air en Feu"] = "Transmutation de l\'Air en Feu",
      ["Transmutation : Terre en Eau"] = "Transmutation de la Terre en Eau",
      ["Transmutation : Eau en Air"] = "Transmutation de l\'Eau en Air",
      ["Elixir de sang de troll puissant"] = "Elixir de sang de troll majeur",
      ["Transmutation : Feu élémentaire"] = "Transmutation du feu élémentaire",
      ["Transmutation primordiale : Air en Feu"] = "Transmutation primordiale (Air en Feu)",
      ["Transmutation primordiale : Terre en Eau"] = "Transmutation primordiale (Terre en Eau)",
      ["Transmutation primordiale : Feu en Terre"] = "Transmutation primordiale (Feu en Terre)",
      ["Transmutation primordiale : Pouvoir"] = "Transmutation primordiale (Pouvoir)",
      ["Transmutation primordiale : Eau en Air"] = "Transmutation primordiale (Eau en Air)",
      ["Transmutation : Diamant tonneterre"] = "Transmutation de diamant tonneterre",
      ["Transmutation : Diamant brûleciel"] = "Transmutation de diamant brûleciel",
      ["Transmutation : Diamant brûleciel"] = "Transmutation de diamant brûleciel",
      ["Transmutation primordiale : Feu en Terre"] = "Transmutation primordiale (Feu en Terre)",
      -- Enchanting
      ["Ench. d\'arme 2M (Intelligence inférieure)"] = "Enchantement d\'arme 2M (Intelligence inférieure)",
      ["Ench. de brassards (Déviation)"] = "Enchantement de brassards (Déviation)",
      ["Ench. de brassards (Déviation inférieure)"] = "Enchantement de brassards (Déviation inférieure)",
      ["Ench. de brassards (Force inférieure)"] = "Enchantement de brassards (Force inférieure)",
      ["Ench. de cape (Agilité mineure)"] = "Enchantement de cape (Agilité mineure)",
      ["Ench. de bouclier (Endurance supérieure)"] = "Enchantement de bouclier (Endurance supérieure)",
      ["Ench. de bottes (Agilité mineure)"] = "Enchantement de bottes (Agilité mineure)",
      ["Ench. de plastron (Mana inférieur)"] = "Enchantement de plastron (Mana inférieur)",
      ["Ench. de plastron (Santé majeure)"] = "Enchantement de plastron (Santé majeure)",
      ["Ench. de cape (Défense excellente)"] = "Enchantement de cape (Défense excellent)",
      ["Ench. d\'arme (Intelligence renforcée)"] = "Enchantement d\'arme (Intelligence renforcée)",
      ["Ench. d\'arme (Esprit renforcé)"] = "Enchantement d\'arme (Esprit renforcé)",
      ["Ench. d\'arme (Force)"] = "Enchantement d\'arme (Force)",
      ["Ench. d\'arme (Agilité)"] = "Enchantement d\'arme (Agilité)",
      ["Ench. de brassards (Régénération de mana)"] = "Enchantement de brassards (Régénération de mana)",
      ["Ench. de cape (Résistance au Feu supérieure)"] = "Enchantement de cape (Résistance au Feu supérieure)",
      ["Ench. de cape (Résistance à la Nature supérieure)"] = "Enchantement de cape (Résistance à la Nature supérieure)",
      ["Ench. d\'arme 2M (Agilité)"] = "Enchantement d\'arme 2M (Agilité)",
      ["Ench. de cape (Pénétration des sorts)"] = "Enchantement de cape (Pénétration des sorts)",
      ["Ench. de gants (Soins majeurs)"] = "Enchantement de gants (Soins majeurs)",
      ["Ench. de gants (Puissance des sorts majeure)"] = "Enchantement de gants (Puissance des sorts majeure)",
      ["Ench. de gants (Frappes précises)"] = "Enchantement de gants (Frappes précises)",
      ["Ench. d\'arme (Soins majeurs)"] = "Enchantement d\'arme (Soins majeurs)",
      ["Ench. de brassards (Soins excellents)"] = "Enchantement de brassards (Soins excellents)",
      ["Ench. de brassards (Soins excellents)"] = "Enchantement de brassards (Soins excellents)",
      ["Ench. de plastron (Carac. exceptionnelles)"] = "Enchantement de plastron (Caractéristiques exceptionelles)",
      ["Ench. de plastron (Carac. exceptionnelles)"] = "Enchantement de plastron (Caractéristiques exceptionelles)",
      ["Ench. d\'anneau (Pouvoir de guérison)"] = "Enchantement d\'anneau (Pouvoir de guérison)",
      ["Ench. d\'anneau (Puissance des sorts)"] = "Enchantement d\'anneau (Puissance des sorts)",
      ["Ench. de bouclier (Intelligence)"] = "Enchantement de bouclier (Intelligence)",
      ["Ench. de bouclier (Endurance majeure)"] = "Enchantement de bouclier (Endurance majeure)",
      ["Ench. d\'anneau (Frappe)"] = "Enchantement d\'anneau (Frappe)",
      ["Ench. d\'arme (Frappe majeure)"] = "Enchantement d\'arme (Frappe majeure)",
      ["Ench. de cape (Esquive)"] = "Enchantement de cape (Esquive)",
      ["Ench. de cape (Camouflage)"] = "Enchantement de cape (Camouflage)",
      ["Ench. de cape (Discrétion)"] = "Enchantement de cape (Discrétion)",
      ["Ench. de cape (Discrétion)"] = "Enchantement de cape (Discrétion)",
      ["Ench. de gants (Agilité excellente)"] = "Enchantement de gants (Agilité excellente)",
      ["Ench. de gants (Menace)"] = "Enchantement de gants (Menace)",
      ["Ench. d\'anneau (Caractéristiques)"] = "Enchantement d\'anneau (Caractéristiques)",
      ["Ench. d\'arme (Agilité supérieure)"] = "Enchantement d\'arme (Agilité supérieure)",
      ["Ench. de plastron (Défense)"] = "Enchantement de plastron (Défense)",
      ["Ench. d\'arme 2M (Massacre)"] = "Enchantement d\'arme 2M (Massacre)",
      ["Ench. d\'arme (Précision)"] = "Enchantement d\'arme (Précision)",
      ["Ench. d\'arme (Berserker)"] = "Enchantement d\'arme (Berserker)",
      ["Ench. d\'arme (Magie noire)"] = "Enchantement d\'arme (Magie noire)",
      ["Ench. d\'arme (Tueur de géant)"] = "Enchantement d\'arme (Tueur de géant)",
      ["Ench. d\'arme (Brise-glace)"] = "Enchantement d\'arme (Brise-glace)",
      ["Ench. d\'arme (Gardevie)"] = "Enchantement d\'arme (Gardevie)",
      ["Ench. d\'arme (Puissance des sorts renforcée)"] = "Enchantement d\'arme (Puissance des sorts renforcée)",
      ["Ench. d\'arme 2M (Plaie-du-Fléau)"] = "Enchantement d\'arme (Plaie du Fléau)",
      ["Ench. d\'arme (Toute-puissance excellente)"] = "Enchantement d\'arme (Toute-puissance excellente)",
      ["Ench. de bottes (Assaut supérieur)"] = "Enchantement de bottes (Assaut supérieur)",
      ["Ench. de bottes (Vitalité rohart)"] = "Enchantement de bottes (Vitalité des roharts)",
      ["Ench. de brassards (Puissance des sorts excellente)"] = "Enchantement de brassards (Puissance des sorts excellente)",
      ["Ench. de brassards (Assaut supérieur)"] = "Enchantement de brassards (Assaut supérieur)",
      ["Ench. de plastron (Caract. puissantes)"] = "Enchantement de plastron (Caractéristiques puissantes)",
      ["Ench. de cape (Vitesse supérieure)"] = "Enchantement de cape (Vitesse supérieure)",
      ["Ench. de cape (Armure puissante)"] = "Enchantement de cape (Armure puissante)",
      ["Ench. de cape (Armure de l\'ombre)"] = "Enchantement de cape (Armure de l\'ombre)",
      ["Ench. de cape (Tisse-titan)"] = "Enchantement de cape (Tisse-titan)",
      ["Ench. de cape (Sagesse)"] = "Enchantement de cape (Sagesse)",
      ["Ench. de gants (Homme d\'armes)"] = "Enchantement de gants (Homme d\'armes)",
      ["Ench. de brassards (Endurance majeure)"] = "Enchantements de brassards (Endurance majeure)",
      ["Ench. de plastron (Résilience exceptionnelle)"] = "Enchantement de plastron (Résilience exceptionnelle)",
      ["Ench. de brassards (Pouvoir de guérison)"] = "Enchantement de brassards (Pouvoir de guérison)",
      ["Ench. de bâton (Puissance des sorts supérieure)"] = "Enchantement de bâton (Puissance des sorts supérieure)",
      -- Engineering
      ["Lanceur de chapelets de feu d\'artifice"] = "Lanceur de chapelets",
      -- Leatherworking
      ["Armure de jambe de cobra du Néant"] = "Armure de jambe en cobra du Néant",
      ["Armure de jambe de cobra du Néant"] = "Armure de jambe en cobra du Néant",
      -- Tailoring
      ["Habit de fête rouge"] = "Habit de fête",
      -- Jewelcrafting
      ["Figurine de crabe en vrai-argent"] = "Crabe en vrai-argent",
      ["Figurine de panthère de perle noire"] = "Panthère de perle noire",
      ["Figurine de crabe de pierre d\'aube"] = "Crabe de pierre d\'aube",
      ["Figurine de crabe de pierre d\'aube"] = "Crabe de pierre d\'aube",
      ["Figurine de sanglier en gangracier"] = "Sanglier en gangracier",
      ["Figurine de serpent de rubis vivant"] = "Serpent de rubis vivant",
      ["Figurine de panthère d\'oeil de nuit"] = "Panthère d\'oeil de nuit",
      ["Figurine de chouette de talasite"] = "Chouette de talasite",
      ["Diamant brûleciel énigmatique"] = "Diamant brûleciel de mystère",
      ["Coeur de don Julio"] = "Cœur de don Julio",
      ["Oeil de nuit régalien"] = "Œil de nuit régalien",
      ["Oeil de lion mystique"] = "Œil de lion mystique",
      ["Topaze monarchique durable"] = "Topaze monarchique solide",
      ["Diamant flambeciel énigmatique"] = "flambeciel énigmatique",
      ["Enorme citrine durable"] = "Enorme citrine solide",
      ["Cristal ombreux mystérieux"] = "ombreux mystérieux",
      ["Opale du crépuscule luminescente"] = "Opale du crépuscule luminescente.",
      ["Cristal ombreux du défenseur"] = "Cristal ombreux de défenseur",
   },

   ["esES"] = {
      -- Alchemy
      ["Transmutar: arcanita"] = "transmutar arcanita",
      ["Transmutar: hierro a oro"] = "transmutar hierro a oro",
      ["Transmutar: mitril a veraplata"] = "transmutar mitril a veraplata",
      ["Transmutar: fuego a tierra"] = "transmutar fuego a tierra",
      ["Transmutar: aire en fuego"] = "transmutar aire en fuego",
      ["Transmutar: tierra a agua"] = "transmutar tierra a agua",
      ["Transmutar: agua a aire"] = "transmutar agua a aire",
      ["Elixir de sangre de trol poderoso"] = "elixir de sangre de trol sublime",
      ["Transmutar: fuego elemental"] = "transmutar fuego elemental",
      ["Transmutar: aire primigenio a fuego primigenio"] = "transmutar aire primigenio en fuego",
      ["Transmutar: tierra primigenia a agua primigenia"] = "transmutar tierra primigenia a agua",
      ["Transmutar: fuego primigenio a tierra primigenia"] = "transmutar fuego primigenio a tierra",
      ["Transmutar: poderío primigenio"] = "transmutar poderío primigenio",
      ["Transmutar: agua primigenia a aire primigenio"] = "transmutar agua primigenia a aire",
      ["Transmutar: diamante de tormenta de tierra"] = "transmutar diamante de tormenta de tierra",
      ["Transmutar: diamante de fuego celeste"] = "transmutar diamante de fuego celeste",
      ["Transmutar: diamante de fuego celeste"] = "transmutar diamante de fuego celeste",
      ["Transmutar: fuego primigenio a tierra primigenia"] = "transmutar fuego primigenio a tierra",
      -- Blacksmithing
      ["Guanteletes de alma de sangre"] = "guanteletes Alma de sangre",
      ["Sobrehombros de alma de sangre"] = "sobrehombros Alma de sangre",
      ["Coraza de alma de sangre"] = "coraza alma de sangre",
      ["Coraza Parraférrea"] = "coraza parraférrea",
      ["Guantes Parraférrea"] = "guantes parraférrea",
      ["Cinturón Parraférrea"] = "cinturón parraférrea",
      ["Cinturón de adamantita encantada"] = "cinturón de adamantita encantado",
      ["Leotardos de adamantita encantada"] = "Leotardos de adamantita encantados",
      -- Enchanting
      ["Encantar arma 2M: intelecto inferior"] = "encantar arma de 2M: intelecto inferior",
      ["Encantar capa: resistencia al Fuego superior"] = "encantar capa: Resistencia al Fuego superior",
      ["Encantar arma 2M: agilidad"] = "encantar arma de 2M: agilidad",
      ["Encantar guantes: golpes precisos"] = "encantar guantes: Golpes precisos",
      ["Encantar arma 2M: masacre"] = "encantar arma de 2M: masacre",
      ["Encantar arma: precisión"] = "encantar arma: Precisión",
      ["Encantar arma 2M: finiquiplaga"] = "encantar arma: Finiquiplaga",
      -- Engineering
      ["Lanzatracas de fuegos de artificio"] = "lanzatracas",
      -- Leatherworking
      ["Brazales de escórpido pesados"] = "brazales de escórpido gruesos",
      ["Yelmo de escórpido pesado"] = "yelmo de escórpido grueso",
      ["Coraza Escupefuego"] = "coraza escupefuego",
      ["Brazales acecharenas"] = "brazales Acecharenas",
      ["Guanteletes acecharenas"] = "guanteletes Acecharenas",
      ["Coraza acecharenas"] = "coraza Acecharenas",
      ["Brazal de acechador vil"] = "brazales de acechador vil",
      ["Brazal de acechador vil"] = "brazales de acechador vil",
      ["Botas de uñagrieta pesadas"] = "botas uñagrieta pesadas",
      ["Leotardos de uñagrieta pesados"] = "leotardos uñagrieta pesados",
      ["Jubón de uñagrieta pesado"] = "jubón de uñagrieta grueso",
      ["Botas de uñagrieta encantadas"] = "botas uñagrieta encantadas",
      ["Guantes de uñagrieta encantados"] = "guantes uñagrieta encantados",
      -- Tailoring
      ["Bolsa de las Sombras de ébano"] = "bolsa de Sombra de ébano",
      ["Hilo de hechizo de oro"] = "hilo de hechizo dorado",
      ["Fin de la Noche"] = "Fin de la noche",
      ["Pantalones rojos de traje festivos"] = "traje de fiesta",
      -- Cooking
      ["Delicia de furia del Loch Modan"] = "delicia de furia de Loch Modan",
      ["Aperitivo para alimañas"] = "aperitivos para alimañas",
      ["Festín gigante"] = "festín gigantesco",
      -- Jewelcrafting
      ["Figurilla: cangrejo de veraplata"] = "cangrejo de veraplata",
      ["Figurilla: pantera de perla negra"] = "pantera de perla negra",
      ["Figurilla: cangrejo de piedra del alba"] = "cangrejo de piedra del alba",
      ["Figurilla: cangrejo de piedra del alba"] = "cangrejo de piedra del alba",
      ["Figurilla: jabalí de acero vil"] = "jabalí de acero vil",
      ["Figurilla: serpiente de rubí vivo"] = "serpiente de rubí vivo",
      ["Figurilla: pantera de ojo de noche"] = "pantera de ojo de noche",
      ["Figurilla: búho de talasita"] = "búho de talasita",
      ["Ojo de noche regio"] = "Ojo de noche majestuoso",
      ["Gran ojo de león"] = "gran Ojo de león",
      ["Ópalo crepuscular regio"] = "ópalo crepuscular majestuoso",
   },

   ["ruRU"] = {
      -- Alchemy
      ["Трансмутация: арканит"] = "трансмутация арканита",
      ["Трансмутация: огонь в землю"] = "трансмутация огня в землю",
      ["Трансмутация: воздух в огонь"] = "трансмутация воздуха в огонь",
      ["Трансмутация: земля в воду"] = "трансмутация земли в воду",
      ["Трансмутация: вода в воздух"] = "трансмутация воды в воздух",
      ["Мощный эликсир тролльей крови"] = "большое зелье тролльей крови",
      ["Трансмутация: первородный огонь"] = "трансмутация первородного огня",
      ["Трансмутация: первичный воздух в огонь"] = "трансмутация изначального воздуха в огонь",
      ["Трансмутация: первичная земля в воду"] = "трансмутация изначальной земли в воду",
      ["Трансмутация: изначальный огонь в землю"] = "трансмутация изначального огня в землю",
      ["Трансмутация: изначальная мощь"] = "трансмутация изначальной мощи",
      ["Трансмутация: первичная вода в воздух"] = "трансмутация изначальной воды в воздух",
      ["Трансмутация: алмаз земной бури"] = "трансмутация алмаза земной бури",
      ["Трансмутация: алмаз небесного огня"] = "трансмутация алмаза небесного огня",
      ["Трансмутация: алмаз небесного огня"] = "трансмутация алмаза небесного огня",
      ["Трансмутация: изначальный огонь в землю"] = "трансмутация изначального огня в землю",
      -- Blacksmithing
      ["Изысканный ториевый одноручный топор"] = "изысканный одноручный топор секач",
      -- Enchanting
      ["Чары для двуручного оружия - интеллект I"] = "чар для двуручного оружия - интеллект I",
      ["Чары для наручей - отражение III"] = "чар для наручей - отражение III",
      ["Чары для наручей - отражение II"] = "чар для наручей - отражение II",
      ["Чары для наручей - сила II"] = "чар для наручей - сила II",
      ["Чары для плаща - ловкость I"] = "чар для плаща - ловкость I",
      ["Чары для щита - выносливость IV"] = "чар для щита - выносливость IV",
      ["Чары для обуви - ловкость I"] = "чар для обуви - ловкость I",
      ["Чары для нагрудника - мана II"] = "чар для нагрудника - мана II",
      ["Чары для нагрудника - здоровье VI"] = "чар для нагрудника - здоровье VI",
      ["Чары для плаща - защита III"] = "чар для плаща - защита III",
      ["Чары для оружия - могучий интеллект"] = "чар для оружия - могучий интеллект",
      ["Чары для оружия - могучий дух"] = "чар для оружия - могучий дух",
      ["Чары для оружия - сила"] = "чар для оружия - сила",
      ["Чары для оружия - ловкость I"] = "чар для оружия - ловкость I",
      ["Чары для наручей - восполнение маны"] = "чар для наручей - восполнение маны",
      ["Чары для плаща - сопротивление огню III"] = "чар для плаща - сопротивление огню III",
      ["Чары для плаща - сопротивление силам природы I"] = "чар для плаща - сопротивление силам природы I",
      ["Чары для двуручного оружия - ловкость I"] = "чар для двуручного оружия - ловкость I",
      ["Чары для плаща - проникающая способность заклинаний"] = "чар для плаща - проникающая способность заклинаний",
      ["Чары для перчаток - лечение I"] = "чар для перчаток - лечение I",
      ["Чары для перчаток - сила заклинаний I"] = "чар для перчаток - сила заклинаний I",
      ["Чары для перчаток - точные удары"] = "чар для перчаток - точные удары",
      ["Чары для оружия - лечение I"] = "чар для оружия - лечение I",
      ["Чары для наручей - лечение II"] = "чар для наручей - лечение II",
      ["Чары для наручей - лечение II"] = "чар для наручей - лечение II",
      ["Чары для нагрудника - все характеристики V"] = "чар для нагрудника - все характеристики V",
      ["Чары для нагрудника - все характеристики V"] = "чар для нагрудника - все характеристики V",
      ["Чары для кольца - целительная сила"] = "чар для кольца - целительная сила",
      ["Чары для кольца - сила заклинаний I"] = "чар для кольца - сила заклинаний I",
      ["Чары для щита - интеллект I"] = "чар для щита - интеллект I",
      ["Чары для щита - выносливость V"] = "чар для щита - выносливость V",
      ["Чары для кольца - удар"] = "чар для кольца - удар",
      ["Чары для оружия - удар VI"] = "чар для оружия - удар VI",
      ["Чары для плаща - уклонение"] = "чар для плаща - уклонение",
      ["Чары для плаща - незаметность"] = "чар для плаща - незаметность",
      ["Чары для плаща - скрытность"] = "чар для плаща - скрытность",
      ["Чары для плаща - скрытность"] = "чар для плаща - скрытность",
      ["Чары для перчаток - ловкость III"] = "чар для перчаток - ловкость III",
      ["Чары для перчаток - угроза"] = "чар для перчаток - угроза",
      ["Чары для кольца - все характеристики"] = "чар для кольца - все характеристики",
      ["Чары для оружия - ловкость II"] = "чар для оружия - ловкость II",
      ["Чары для нагрудника - защита I"] = "чар для нагрудника - защита I",
      ["Чары для двуручного оружия - резня"] = "чар для двуручного оружия - резня",
      ["Чары для оружия - меткость"] = "чар для оружия - точность",
      ["Чары для оружия - берсерк"] = "чар для оружия - берсерк",
      ["Чары для оружия - черная магия"] = "чар для оружия - черная магия",
      ["Чары для оружия - истребитель гигантов"] = "чар для оружия - истребитель гигантов",
      ["Чары для оружия - ледорез"] = "чар для оружия - ледорез",
      ["Чары для оружия - оберег"] = "чар для оружия - оберег",
      ["Чары для оружия - сила заклинаний III"] = "чар для оружия - сила заклинаний III",
      ["Чары для двуручного оружия - проклятие Плети"] = "чар для оружия - проклятие Плети",
      ["Чары для оружия - могущество III"] = "чар для оружия - могущество III",
      ["Чары для обуви - штурм II"] = "чар для обуви - штурм II",
      ["Чары для обуви - живучесть клыкарра"] = "чар для обуви - живучесть клыкарра",
      ["Чары для наручей - сила заклинаний III"] = "чар для наручей - сила заклинаний III",
      ["Чары для наручей - штурм II"] = "чар для наручей - штурм II",
      ["Чары для нагрудника - все характеристики VII"] = "чар для нагрудника - все характеристики VII",
      ["Чары для плаща - скорость II"] = "чар для плаща - скорость II",
      ["Чары для плаща - могучая броня"] = "чар для плаща - могучая броня",
      ["Чары для плаща - теневая броня"] = "чар для плаща - теневая броня",
      ["Чары для плаща - ткань титанов"] = "чар для плаща - ткань титанов",
      ["Чары для плаща - мудрость"] = "чар для плаща - мудрость",
      ["Чары для перчаток - оружейник"] = "чар для перчаток - оружейник",
      ["Чары для наручей - выносливость VI"] = "чар для наручей - выносливость V",
      ["Чары для нагрудника - устойчивость II"] = "чар для нагрудника - устойчивость II",
      ["Чары для наручей - целительная сила"] = "чар для наручей - целительная сила",
      ["Чары для посоха - сила заклинаний II"] = "чар для посоха - сила заклинаний II",
      -- Leatherworking
      ["Рукавицы дьявозавра"] = "рукавицы девизавра",
      ["Пояс гончей Недр"] = "пояс пса недр",
      ["Сапоги гончей Недр"] = "сапоги пса недр",
      -- Tailoring
      ["Праздничный красный костюм"] = "праздничный костюм",
      ["Сумка Бездны"] = "сумка бездны",
      -- Jewelcrafting
      ["Статуэтка краба из истинного серебра"] = "краб из истинного серебра",
      ["Статуэтка пантеры из черного жемчуга"] = "пантера из черного жемчуга",
      ["Статуэтка краба из зоревика"] = "краб из зоревика",
      ["Статуэтка краба из зоревика"] = "краб из зоревика",
      ["Статуэтка вепря из оскверненной стали"] = "Вепрь из оскверненной стали",
      ["Статуэтка змеи из животворного рубина"] = "змея из животворного рубина",
      ["Статуэтка пантеры из ока ночи"] = "пантера из ока ночи",
      ["Статуэтка таласситовой совы"] = "таласситовая сова",
      ["Прочный золотой дренит"] = "твердый золотой дренит",
      ["Королевский сумрачный дренит"] = "королевский сумеречный дренит",
      ["Изменчивый сумрачный дренит"] = "изменчивый сумеречный дренит",
      ["Царственный сумрачный дренит"] = "царственный сумеречный дренит",
      ["Светящийся сумрачный дренит"] = "светящийся сумеречный дренит",
      ["Цельный лазурный лунный камень"] = "твердый лазурный лунный камень",
      ["Рельефная пунцовая шпинель"] = "рельефная алая шпинель",
      ["Яркая пунцовая шпинель"] = "яркая алая шпинель",
      ["Изысканная пунцовая шпинель"] = "изысканная алая шпинель",
      ["Руническая пунцовая шпинель"] = "руническая алая шпинель",
      ["Цельный неземной сапфир"] = "твердый неземной сапфир",
      ["Изящная пунцовая шпинель"] = "изящная алая шпинель",
      ["Каплевидная пунцовая шпинель"] = "каплевидная алая шпинель",
      ["Прочный львиный глаз"] = "твердый львиный глаз",
      ["Пунцовое солнце"] = "багровое солнце",
      ["Мощный морской изумруд"] = "могущественный морской изумруд",
      ["Мягкий львиный глаз"] = "горящий львиный глаз",
      ["Рельефная пунцовая шпинель"] = "рельефная алая шпинель",
      ["Каплевидная пунцовая шпинель"] = "каплевидная алая шпинель",
      ["Цельный неземной сапфир"] = "твердый неземной сапфир",
      ["Изящная пунцовая шпинель"] = "изящная алая шпинель",
      ["Руническая пунцовая шпинель"] = "руническая алая шпинель",
      ["Яркая пунцовая шпинель"] = "яркая алая шпинель",
      ["Изысканная пунцовая шпинель"] = "изысканная алая шпинель",
      ["Прочный львиный глаз"] = "твердый львиный глаз",
      ["Блистательная пунцовая шпинель"] = "блистательная алая шпинель",
      ["Великий львиный глаз"] = "большой львиный глаз",
      ["Мощный морской изумруд"] = "могущественный морской изумруд",
      ["Мягкий львиный глаз"] = "горящий львиный глаз",
      ["Угасающий алмаз небесного сияния"] = "тлеющий алмаз небесного сияния",
      ["Усиленный лесной изумруд"] = "заряженный лесной изумруд",
      ["Мощный талассит"] = "могущественный талассит",
      ["Блистающий императорский топаз"] = "блистающий королевский топаз",
      ["Светоносный императорский топаз"] = "светоносный королевский топаз",
      ["Могущественный императорский топаз"] = "могущественный королевский топаз",
      ["Мягкое сияние осени"] = "мимолетное сияние осени",
      ["Мягкий зоревик"] = "горящий зоревик",
      ["Мягкое Око дракона"] = "быстрое око дракона",
      ["Тревожный императорский топаз"] = "тревожный королевский топаз",
      ["Прочное сияние осени"] = "яркое сияние осени",
      ["Прочное око дракона"] = "твердое око дракона",
      ["Цельное око дракона"] = "твердое око дракона",
      ["Цельный небесный сапфир"] = "твердый небесный сапфир",
      ["Застывший императорский топаз"] = "застывший королевский топаз",
      ["Сокрытый императорский топаз"] = "сокрытый королевский топаз",
      ["Надежный императорский топаз"] = "надежный королевский топаз",
      ["Наделенный силой императорский топаз"] = "наделенный силой королевский топаз",
      ["Жалкий алмаз небесного сияния"] = "мизерный алмаз небесного сияния",
      ["Прозрачный императорский топаз"] = "прозрачный королевский топаз",
      ["Мистическое сияние осени"] = "таинственное сияние осени",
      ["Глянцевый императорский топаз"] = "глянцевый королевский топаз",
      ["Таинственный сумрачный кристалл"] = "таинственный теневой кристалл",
      ["Мерцающий императорский топаз"] = "мерцающий королевский топаз",
      ["Гладкое сияние осени"] = "мягкое сияние осени",
      ["Гибельный императорский топаз"] = "гибельный королевский топаз",
      ["Сумрачный кристалл защитника"] = "теневой кристалл защитника",
   },

   ["zhTW"] = {
   },

}

