-- THIS CONTENTS OF THIS FILE IS AUTO-GENERATED BY THE WOWACE PACKAGER
-- Please use the Localization App on WoWAce to update this
-- at http://www.wowace.com/projects/gather-hud/localization/

--Translated by StingerSoft (Eritnull aka Шептун)
local AceLocale = LibStub:GetLibrary("AceLocale-3.0")
local L = AceLocale:NewLocale("GatherHud", "ruRU")
if not L then return end

L["A depth effect that controls how much the size of the icons changes for nodes in the near and far distance"] = "Эффект глубины иконок который контролирует какой размер иконок будет отображаться для ближних и дальних нодов"
L["Angle of view"] = "Угол просмотра"
L["Displays a circle border representing the drawing area of the hud"] = "Отображение круглых краев зоны показа индикатора"
L["Displays a letter N on the border of the hud circle to indicate the North direction"] = "Отображение буквы N на крае круга индикатора для обозначения направление СЕВЕРА"
L["Do not allow the GatherHud camera pitch to go below this angle"] = "Не позволяет GatherHud углу наклона камеры перейти ниже данного значения"
L["Enable GatherHud"] = "Включить GatherHud"
L["Enable or disable GatherHud"] = "Включить/Выключить GatherHud"
L["gatherhud"] = "gatherhud"
L["GatherHud"] = "GatherHud"
L["GATHERHUD_DESC"] = [=[GatherHud это очень хорошо настраиваемый индикатор который позволяет быстро обнаружить расположенные поблизости ноды. GatherHud по выбору поддерживает маршруты.

Принимать к сведению что вы можете прокрутить ваше колесо мыши над ползунком для прокрутки.]=]
L["GatherHud Icon Options"] = "Настройки иконки GatherHud"
L["GatherHud Options"] = "Настройки GatherHud"
L["GatherHud Routes Support"] = "Поддержка маршрутов"
L["Hud Alpha"] = "Прозрачность"
L["Hud map radius"] = "Радиус карты"
L["Hud Width"] = "Ширина"
L["Hud X-Position"] = "Позиция по X"
L["Hud Y-Position"] = "Позиция по Y"
L["Icon alpha"] = "Прозрачность иконки"
L["Icon depth effect"] = "Эффект глубины иконок"
L["Icon size"] = "Размер иконки"
L["Keybind to toggle GatherHud"] = "Клавиши для GatherHud"
L["Minimum Pitch"] = "Минимальный угол наклона"
L["Self color"] = "Цвет"
L["Show Hud circle"] = "Круг индикатор"
L["Show North indicator"] = "Обозначение Севера (N)"
L["Show Routes in the hud"] = "Отображение маршрутов в индикаторе"
L["The alpha transparency of the hud"] = "Прозрачность индикатора"
L["The alpha transparency of the icons"] = "Прозрачность иконки"
L["The angle of elevation from the horizontal plane to view the hud at"] = "Угол возвышения от горизонтальной плоскости просмотра индикатора"
L["The color of the small circle that represents yourself in the center of the hud"] = "Цвет маленького круга в центре индикатора"
L["The pixel width of the hud. In effect, this controls the scaling of the entire hud"] = "Ширина индикатора в пикселях."
L["The radius in yards the hud will draw nodes for from your position"] = "Радиус отображения нодов в ярдах от вашей позиции в индикаторе"
L["The size of the icons displayed in the hud"] = "Размер иконок отображаемых на индикаторе"
L["The X offset coordinate of the hud from the center of the screen"] = "Смещение индикатора по X от центра экрана"
L["The Y offset coordinate of the hud from the center of the screen"] = "Смещение индикатора по Y от центра экрана"
L["Use Camera Pitch"] = "Угол наклона камеры"
L["Use Minimum Pitch"] = "Мин. угол наклона"
L["Use the camera pitch instead of a user-specified angle"] = "Использовать угол наклона камеры в зависимости от заданного игроком угла просмотра"

