-- THIS CONTENTS OF THIS FILE IS AUTO-GENERATED BY THE WOWACE PACKAGER
-- Please use the Localization App on WoWAce to update this
-- at http://www.wowace.com/projects/gather-hud/localization/

local AceLocale = LibStub:GetLibrary("AceLocale-3.0")
local L = AceLocale:NewLocale("GatherHud", "koKR")
if not L then return end

-- L["A depth effect that controls how much the size of the icons changes for nodes in the near and far distance"] = "A depth effect that controls how much the size of the icons changes for nodes in the near and far distance"
-- L["Angle of view"] = "Angle of view"
-- L["Displays a circle border representing the drawing area of the hud"] = "Displays a circle border representing the drawing area of the hud"
-- L["Displays a letter N on the border of the hud circle to indicate the North direction"] = "Displays a letter N on the border of the hud circle to indicate the North direction"
-- L["Do not allow the GatherHud camera pitch to go below this angle"] = "Do not allow the GatherHud camera pitch to go below this angle"
-- L["Enable GatherHud"] = "Enable GatherHud"
-- L["Enable or disable GatherHud"] = "Enable or disable GatherHud"
-- L["gatherhud"] = "gatherhud"
-- L["GatherHud"] = "GatherHud"
--[==[ L["GATHERHUD_DESC"] = [=[GatherHud is a highly configurable hud that allows you to quickly see where the nearby nodes are. GatherHud optionally supports Routes.

Note that you can scroll your mouse wheel while over the sliders to step by 1.]=] ]==]
-- L["GatherHud Icon Options"] = "GatherHud Icon Options"
-- L["GatherHud Options"] = "GatherHud Options"
-- L["GatherHud Routes Support"] = "GatherHud Routes Support"
-- L["Hud Alpha"] = "Hud Alpha"
-- L["Hud map radius"] = "Hud map radius"
-- L["Hud Width"] = "Hud Width"
-- L["Hud X-Position"] = "Hud X-Position"
-- L["Hud Y-Position"] = "Hud Y-Position"
-- L["Icon alpha"] = "Icon alpha"
-- L["Icon depth effect"] = "Icon depth effect"
-- L["Icon size"] = "Icon size"
-- L["Keybind to toggle GatherHud"] = "Keybind to toggle GatherHud"
-- L["Minimum Pitch"] = "Minimum Pitch"
-- L["Self color"] = "Self color"
-- L["Show Hud circle"] = "Show Hud circle"
-- L["Show North indicator"] = "Show North indicator"
-- L["Show Routes in the hud"] = "Show Routes in the hud"
-- L["The alpha transparency of the hud"] = "The alpha transparency of the hud"
-- L["The alpha transparency of the icons"] = "The alpha transparency of the icons"
-- L["The angle of elevation from the horizontal plane to view the hud at"] = "The angle of elevation from the horizontal plane to view the hud at"
-- L["The color of the small circle that represents yourself in the center of the hud"] = "The color of the small circle that represents yourself in the center of the hud"
-- L["The pixel width of the hud. In effect, this controls the scaling of the entire hud"] = "The pixel width of the hud. In effect, this controls the scaling of the entire hud"
-- L["The radius in yards the hud will draw nodes for from your position"] = "The radius in yards the hud will draw nodes for from your position"
-- L["The size of the icons displayed in the hud"] = "The size of the icons displayed in the hud"
-- L["The X offset coordinate of the hud from the center of the screen"] = "The X offset coordinate of the hud from the center of the screen"
-- L["The Y offset coordinate of the hud from the center of the screen"] = "The Y offset coordinate of the hud from the center of the screen"
-- L["Use Camera Pitch"] = "Use Camera Pitch"
-- L["Use Minimum Pitch"] = "Use Minimum Pitch"
-- L["Use the camera pitch instead of a user-specified angle"] = "Use the camera pitch instead of a user-specified angle"

