-- THIS CONTENTS OF THIS FILE IS AUTO-GENERATED BY THE WOWACE PACKAGER
-- Please use the Localization App on WoWAce to update this
-- at http://www.wowace.com/projects/gather-hud/localization/

-- frFR Localization file, by pettigrow
local AceLocale = LibStub:GetLibrary("AceLocale-3.0")
local L = AceLocale:NewLocale("GatherHud", "frFR")
if not L then return end

L["A depth effect that controls how much the size of the icons changes for nodes in the near and far distance"] = "L'effet de profondeur contrôle à quel point la taille des icônes change pour les noeuds proches et lointains."
L["Angle of view"] = "Angle de vue"
L["Displays a circle border representing the drawing area of the hud"] = "Affiche un cercle représentant la zone de croquis du HUD."
L["Displays a letter N on the border of the hud circle to indicate the North direction"] = "Affiche la lettre N sur le bord du cercle du HUD pour indiquer où se trouve le nord."
-- L["Do not allow the GatherHud camera pitch to go below this angle"] = "Do not allow the GatherHud camera pitch to go below this angle"
L["Enable GatherHud"] = "Activer GatherHud"
L["Enable or disable GatherHud"] = "Active ou désactive GatherHud."
L["gatherhud"] = "gatherhud"
L["GatherHud"] = "GatherHud"
L["GATHERHUD_DESC"] = [=[GatherHud est un HUD ("Head Up Display" ou "Affichage tête haute" en français) hautement configurable qui vous permet de voir rapidement où sont les nœuds les plus proches. GatherHud supporte Routes (optionnel).

Notez que vous pouvez jouer avec la roulette de votre souris sur les sliders pour modifier la valeur par 1.]=]
L["GatherHud Icon Options"] = "Options des icônes de GatherHud"
L["GatherHud Options"] = "Options de GatherHud"
L["GatherHud Routes Support"] = "Support de Routes par GatherHud"
L["Hud Alpha"] = "Transparence du HUD"
L["Hud map radius"] = "Rayon du HUD"
L["Hud Width"] = "Largeur du HUD"
L["Hud X-Position"] = "Position en X du HUD"
L["Hud Y-Position"] = "Position en Y du HUD"
L["Icon alpha"] = "Transparence des icônes"
L["Icon depth effect"] = "Effet de profondeur des icônes"
L["Icon size"] = "Taille des icônes"
-- L["Keybind to toggle GatherHud"] = "Keybind to toggle GatherHud"
-- L["Minimum Pitch"] = "Minimum Pitch"
L["Self color"] = "Couleur du joueur"
L["Show Hud circle"] = "Afficher le cercle du HUD"
L["Show North indicator"] = "Indiquer le nord"
L["Show Routes in the hud"] = "Afficher Routes dans le HUD"
L["The alpha transparency of the hud"] = "Détermine la transparence de l'HUD."
L["The alpha transparency of the icons"] = "Détermine la transparence des icônes affichées sur le HUD."
L["The angle of elevation from the horizontal plane to view the hud at"] = "Détermine l'angle d'élévation par rapport au plan horizontal de la vue du HUD."
L["The color of the small circle that represents yourself in the center of the hud"] = "Détermine la couleur du petit cercle qui vous représente au centre du HUD."
L["The pixel width of the hud. In effect, this controls the scaling of the entire hud"] = "Détermine la largeur du HUD. En réalité, ceci contrôle l'échelle de tout le HUD."
L["The radius in yards the hud will draw nodes for from your position"] = "Détermine le rayon en mètres par rapport à votre position dans lequel les nœuds seront afffichés."
L["The size of the icons displayed in the hud"] = "Détermine la taille des icônes affichées sur le HUD."
L["The X offset coordinate of the hud from the center of the screen"] = "Détermine le décalage en X du HUD par rapport au centre de l'écran."
L["The Y offset coordinate of the hud from the center of the screen"] = "Détermine le décalage en Y du HUD par rapport au centre de l'écran."
-- L["Use Camera Pitch"] = "Use Camera Pitch"
-- L["Use Minimum Pitch"] = "Use Minimum Pitch"
-- L["Use the camera pitch instead of a user-specified angle"] = "Use the camera pitch instead of a user-specified angle"

